name: 'housamoAutoLogin'

on:
  schedule:
    - cron: '0  15,3 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: pip install requests
    - name: Read anth_key & Login  #读取账号并登录
      env: 
        auth_keys: ${{ toJson(secrets) }}   # 由secrets 提供auth_key
      run: python Login.py
    - name: Commit & Push  #更新仓库保持活跃
      uses: EndBug/add-and-commit@v4
      with:
        author_name: chedandan
        author_email: 243304341@qq.com
        message: "action update"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
